First pull request for Enumerable Numbers project
bruna-genz/enumerable-numbers pull request #1
Opened 2019-09-13 21:46 UTC by bruna-genz

2019-09-14 01:04 UTC, maelfosso requested changes
HEllo @bruna-genz ,

# :clap: Nice job :smile: 

Please take a look below to do the needed changes.
Kindly make those changes and submit a new code review request.

Thank

2019-09-14 01:04 UTC, maelfosso commented on enumerable_number.rb
> +  end
Sorry :disappointed:  there are some scenario not implemented
```ruby
rb(main):029:0> ary.count 
=> 4
irb(main):030:0> ary.my_count 
Traceback (most recent call last):
        5: from /home/elvisfosso/.rbenv/versions/2.5.1/bin/irb:11:in `<main>'
        4: from (irb):30
        3: from enumerable_number.rb:73:in `my_count'
        2: from enumerable_number.rb:7:in `my_each'
        1: from enumerable_number.rb:74:in `block in my_count'
LocalJumpError (no block given (yield))
```
Same thing here
```ruby
irb(main):031:0> ary.count(2)
=> 2
irb(main):032:0> ary.my_count(2)
Traceback (most recent call last):
        3: from /home/elvisfosso/.rbenv/versions/2.5.1/bin/irb:11:in `<main>'
        2: from (irb):32
        1: from enumerable_number.rb:70:in `my_count'
ArgumentError (wrong number of arguments (given 1, expected 0))
```

Error when counting, now
```irb(main):033:0> ary.count{ |x| x%2==0 }
=> 3
irb(main):034:0> ary.my_count{ |x| x%2==0 }
=> 4
```

2019-09-14 01:04 UTC, maelfosso commented on enumerable_number.rb
> +end
Sorry there are errors
```ruby
irb(main):037:0> [1, 2, 4, 2].inject { |sum, n| sum + n } 
=> 9
irb(main):038:0> [1, 2, 4, 2].my_inject { |sum, n| sum + n } 
=> 10
irb(main):040:0> [1, 2, 4, 2].inject(2) { |sum, n| sum + n } 
=> 11
irb(main):041:0> [1, 2, 4, 2].my_inject(2) { |sum, n| sum + n } 
=> 10
```

2019-09-14 15:22 UTC, maelfosso requested changes
Hello @bruna-genz 

Really nice improvement :smile: 
But there is just one bug to fix.
Take a look at the `my_inject` method.

Kindly make the changes and submit a new code review request, please.

2019-09-14 15:22 UTC, maelfosso commented on enumerable_number.rb
> +end
You fixed those bugs :smile: 
But there is a new bugs
```ruby
irb(main):007:0> [1, 2, 4, 2].inject { |prod, n| prod * n }
=> 16
irb(main):008:0> [1, 2, 4, 2].my_inject { |prod, n| prod * n }
=> 0
```

2019-09-14 15:22 UTC, maelfosso commented on enumerable_number.rb
> +  end
Great :+1: 
:smile:

2019-09-16 20:40 UTC, samgaco approved these changes
Hi @bruna-genz :high_brightness: 

The project is approved :white_check_mark: , you may merge to the master branch and submit the project completion form. Regards :hammer: 

------------------------

* ###### STATUS OF THE PROJECT: APPROVED :heavy_check_mark:

2019-09-16 20:40 UTC, samgaco commented on enumerable_number.rb
> +  def my_inject(arg1 = nil, arg2 = nil)
working now :100:

2019-09-16 20:45 UTC, merged