RSpec tests for Enumerable Numbers
bruna-genz/enumerable-numbers pull request #3
Opened 2019-10-04 16:15 UTC by bruna-genz

In this branch, I created test cases for six methods of my enumerable numbers project. There are some tests that have failed, exposing that I didn't consider all possible scenarios for some of my methods.

2019-10-04 16:18 UTC, bruna-genz commented
The linter errors are coming from the spec_helper.rb file.

2019-10-04 20:24 UTC, samgaco requested changes
Hi @bruna-genz :high_brightness: 

Some tests seem to be failing when running rspec. Should be addressed.

Please submit back once you are done.


reference:
```

Failures:

  1) Enumerable my_each returns an enumerable if no code block is given
     Failure/Error: yield(self[i])
     
     LocalJumpError:
       no block given (yield)
     # ./lib/enumerable_number.rb:7:in `my_each'
     # ./spec/enumerables_spec.rb:16:in `block (3 levels) in <top (required)>'

  2) Enumerable my_select returns an enumerable if no code block is given
     Failure/Error: result << element if yield(element)
     
     LocalJumpError:
       no block given (yield)
     # ./lib/enumerable_number.rb:23:in `block in my_select'
     # ./lib/enumerable_number.rb:7:in `my_each'
     # ./lib/enumerable_number.rb:22:in `my_select'
     # ./spec/enumerables_spec.rb:36:in `block (3 levels) in <top (required)>'

  3) Enumerable my_any? when an argument is given returns true if any of the elements is === to the argument
     Failure/Error:
       def my_any?
         result = false
         if block_given?
           my_each do |element|
             result = true if yield(element)
           end
         else
           my_each do |element|
             result = true if element
           end
     
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
     # ./lib/enumerable_number.rb:42:in `my_any?'
     # ./spec/enumerables_spec.rb:93:in `block (4 levels) in <top (required)>'

  4) Enumerable my_inject when the operator is passed as a symbol without other argument passes each element and accumulated each result sequentially
     Failure/Error: operation = arg2.to_proc
     
     NoMethodError:
       undefined method `to_proc' for nil:NilClass
     # ./lib/enumerable_number.rb:107:in `my_inject'
     # ./spec/enumerables_spec.rb:149:in `block (4 levels) in <top (required)>'

Finished in 0.00636 seconds (files took 0.08046 seconds to load)
24 examples, 4 failures
```


-----------------

* ###### STATUS OF THE PROJECT: REQUESTED CHANGES :stop_sign:

2019-10-04 20:24 UTC, samgaco commented on spec/enumerables_spec.rb
> +    end
some tests are failing when running rspec

2019-10-04 20:24 UTC, samgaco commented on spec/enumerables_spec.rb
> +      array.my_each { |element| output << element }
all the specs should be wrapped within describe blocks, [reference](https://github.com/rubocop-hq/rspec-style-guide#empty-lines-around-examples).

2019-10-08 00:56 UTC, bolah2009 approved these changes
## Nice job implementing all suggested changes.

### It's a :+1: from me,

You can merge to master. 

#### I strongly recommend you `fix` the linter warnings before merging. You can do this by running `rubocop -a`.

2019-10-08 15:51 UTC, merged